# Generated by Django 5.2.5 on 2025-09-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Womencare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegetable',
            name='Phone_Number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
