# Generated by Django 5.2.5 on 2025-09-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Womencare', '0002_alter_collegetable_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegetable',
            name='Address',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
