# Generated by Django 5.2.5 on 2025-11-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Womencare', '0003_collegetable_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencytable',
            old_name='login_id',
            new_name='USERID',
        ),
        migrations.AlterField(
            model_name='teachertable',
            name='Phone_number',
            field=models.BigIntegerField(blank=True, max_length=20, null=True),
        ),
    ]
