# Generated by Django 5.2.5 on 2025-11-22 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Womencare', '0004_rename_login_id_emergencytable_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencytable',
            name='USERID',
        ),
        migrations.AddField(
            model_name='emergencytable',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Womencare.usertable'),
        ),
    ]
