# Generated by Django 5.2.5 on 2025-11-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Womencare', '0005_remove_emergencytable_userid_emergencytable_login_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencytable',
            old_name='login_id',
            new_name='USERID',
        ),
    ]
