# Generated by Django 5.2.5 on 2025-11-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Womencare', '0006_rename_login_id_emergencytable_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalhealthsupporttable',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealthsupporttable',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
