# Generated by Django 5.2.5 on 2025-11-22 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Womencare', '0007_mentalhealthsupporttable_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthsupporttable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentalhealthsupporttable',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Womencare.usertable'),
        ),
    ]
