# Generated by Django 5.2.5 on 2025-11-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Womencare', '0008_alter_mentalhealthsupporttable_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainttable',
            name='complaint_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='complainttable',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
