# Generated by Django 5.2.5 on 2026-01-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Womencare', '0009_complainttable_complaint_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
